/**
 * Hepsiburada Product Import API Route
 * POST /api/hb-import
 * 
 * CRITICAL: This endpoint requires multipart/form-data with specific rules:
 * 1. File parameter name MUST be "file" (not "files" or anything else)
 * 2. Content-Type MUST be "application/json; charset=utf-8" for the JSON file
 * 3. Filename should be "integrator.json"
 * 4. Let FormData auto-generate boundary (do NOT set manually)
 */

import { NextRequest, NextResponse } from 'next/server';
import FormData from 'form-data';
import axios from 'axios';

// Hepsiburada API Configuration
const HB_CONFIG = {
  API_URL: 'https://mpop-sit.hepsiburada.com/product/api/products/import?version=1',
  USERNAME: '3f95e71f-c39e-4266-9eb4-c154807e87f7', // Merchant ID (Username)
  PASSWORD: 'd8rCXfXqWJW2', // Secret Key
  USER_AGENT: 'aserai_dev',
  FILE_PARAM_NAME: 'file', // CRITICAL: Must be exactly "file"
  FILE_NAME: 'integrator.json',
};

// Generate Basic Auth token
function generateBasicAuth(username: string, password: string): string {
  const credentials = `${username}:${password}`;
  return Buffer.from(credentials).toString('base64');
}

export async function POST(request: NextRequest) {
  try {
    // Get JSON data from frontend
    const body = await request.json();
    
    console.log('📦 Hepsiburada Product Import Request (multipart/form-data)');
    console.log('📄 JSON Data:', JSON.stringify(body, null, 2));

    // Generate Basic Auth token
    const authToken = generateBasicAuth(HB_CONFIG.USERNAME, HB_CONFIG.PASSWORD);
    
    console.log('🔐 Using credentials:', {
      username: HB_CONFIG.USERNAME.substring(0, 5) + '...',
      password: HB_CONFIG.PASSWORD.substring(0, 5) + '...',
      userAgent: HB_CONFIG.USER_AGENT,
    });

    // Create form-data instance
    const form = new FormData();
    
    // Convert JSON to string
    const jsonString = JSON.stringify(body);
    
    // CRITICAL: Convert string to Buffer - Hepsiburada requires actual file content
    const jsonBuffer = Buffer.from(jsonString, 'utf-8');
    
    // Append JSON as file with proper content-type
    // This is the EXACT format Hepsiburada expects
    form.append(HB_CONFIG.FILE_PARAM_NAME, jsonBuffer, {
      filename: HB_CONFIG.FILE_NAME,
      contentType: 'application/json; charset=utf-8',
    });

    console.log('\n🔥 ============= GERÇEK HTTP İSTEĞİ =============');
    console.log('📍 URL:', HB_CONFIG.API_URL);
    console.log('🔧 Method: POST');
    console.log('📋 Headers:');
    console.log('   Authorization:', `Basic ${authToken}`);
    console.log('   User-Agent:', HB_CONFIG.USER_AGENT);
    console.log('   Content-Type: multipart/form-data; boundary=[auto-generated by form-data]');
    console.log('📦 Body:');
    console.log('   Format: multipart/form-data');
    console.log('   File parameter name:', HB_CONFIG.FILE_PARAM_NAME);
    console.log('   File name:', HB_CONFIG.FILE_NAME);
    console.log('   File content-type: application/json; charset=utf-8');
    console.log('   Buffer size:', jsonBuffer.length, 'bytes');
    console.log('   JSON Content (first 500 chars):');
    console.log('   ', jsonString.substring(0, 500));
    console.log('\n🔐 Auth Token (Base64):');
    console.log('   ', authToken);
    console.log('\n🔓 Decoded Credentials:');
    console.log('   ', `${HB_CONFIG.USERNAME}:${HB_CONFIG.PASSWORD}`);
    console.log('🔥 ============================================\n');

    // Send request using AXIOS (guaranteed to work with form-data)
    const hbResponse = await axios.post(HB_CONFIG.API_URL, form, {
      headers: {
        ...form.getHeaders(), // This is CRITICAL - adds proper boundary
        'Authorization': `Basic ${authToken}`,
        'User-Agent': HB_CONFIG.USER_AGENT,
      },
      maxBodyLength: Infinity,
      maxContentLength: Infinity,
      validateStatus: () => true, // Don't throw on any status code
    });

    console.log('📊 Hepsiburada API Status:', hbResponse.status);
    console.log('📊 Hepsiburada API Headers:', hbResponse.headers);

    // Get response data (axios automatically parses JSON)
    const apiResponse = hbResponse.data;
    const responseText = typeof apiResponse === 'string' ? apiResponse : JSON.stringify(apiResponse);
    
    console.log('📄 Hepsiburada API Response Text:', responseText);

    // Prepare response
    const timestamp = new Date().toISOString();

    if (hbResponse.status >= 200 && hbResponse.status < 300) {
      // Success response
      const response = {
        success: true,
        message: '✅ Ürün başarıyla Hepsiburada\'ya yüklendi (multipart/form-data with form-data package)!',
        statusCode: hbResponse.status,
        data: apiResponse,
        timestamp,
      };

      console.log('✅ Success response:', response);
      return NextResponse.json(response, { status: 200 });
    } else {
      // Error response
      const errors: string[] = [];
      
      // Check for authentication/authorization errors
      if (hbResponse.status === 401) {
        errors.push('🔐 KİMLİK DOĞRULAMA HATASI (401 Unauthorized)');
        errors.push('Servis anahtarı veya secret key hatalı olabilir');
      } else if (hbResponse.status === 403) {
        errors.push('🔒 ERİŞİM ENGELLENDİ (403 Forbidden)');
        errors.push('Authentication bilgileri doğru ama yetki yok veya API endpoint hatalı');
        errors.push('Test ortamı için doğru endpoint kullanıldığından emin olun');
      }
      
      // Extract errors from response
      if (apiResponse.errors && Array.isArray(apiResponse.errors)) {
        apiResponse.errors.forEach((error: any) => {
          const errorMsg = `[${error.field || 'Genel'}] ${error.message || error}`;
          errors.push(errorMsg);
        });
      } else if (apiResponse.message) {
        errors.push(apiResponse.message);
      } else if (apiResponse.error) {
        errors.push(apiResponse.error);
      } else if (errors.length === 0) {
        errors.push(`HTTP ${hbResponse.status}: ${hbResponse.statusText || 'Error'}`);
      }

      const response = {
        success: false,
        message: '❌ Hepsiburada API hatası',
        statusCode: hbResponse.status,
        data: apiResponse,
        errors,
        timestamp,
      };

      console.log('❌ Error response:', response);
      return NextResponse.json(response, { status: 200 }); // Return 200 to frontend but with success: false
    }
  } catch (error: unknown) {
    console.error('❌ Internal API error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Bilinmeyen hata';
    
    const response = {
      success: false,
      message: '❌ İç sunucu hatası',
      errors: [errorMessage],
      timestamp: new Date().toISOString(),
    };

    return NextResponse.json(response, { status: 500 });
  }
}

export async function GET(request: NextRequest) {
  return NextResponse.json({
    success: true,
    message: 'Hepsiburada Product Import API (multipart/form-data with form-data package)',
    usage: {
      endpoint: '/api/hb-import',
      method: 'POST',
      description: 'Hepsiburada\'ya ürün gönderir (multipart/form-data + JSON file)',
      format: 'multipart/form-data with application/json; charset=utf-8',
      config: {
        apiUrl: HB_CONFIG.API_URL,
        username: HB_CONFIG.USERNAME.substring(0, 5) + '...',
        userAgent: HB_CONFIG.USER_AGENT,
        fileParamName: HB_CONFIG.FILE_PARAM_NAME,
        fileName: HB_CONFIG.FILE_NAME,
      },
    },
  });
}
